#include <stdio.h>

int main()
{
    int a,b,c,d,e,f,xx=0;
    while(scanf("%d%d%d%d%d%d",&a,&b,&c,&d,&e,&f)&&a+b+c+d+e+f!=0)
    {
        xx=f;
        if(e>0)
        {
            xx+=e;
            a-=11*e;
        }
        if(d>0)
        {
            xx+=d;
            b-=5*d;
            if(b<0)
            {
                a+=4*b;
            }
        }
        if(c>0)
        {
            xx+=c/4;
            c=c%4;
            if(c>0)
            {
                xx++;
                if(c==1)
                {
                    if(b>0)
                    {
                        b-=5;
                        a-=7;
                    }
                    else
                    {
                        a-=27;
                    }
                }
                else if(c==2)
                {
                    if(b>0)
                    {
                        b-=3;
                        a-=6;
                    }
                    else
                    {
                        a-=18;
                    }
                }
                else if(c==3)
                {
                    if(b>0)
                    {
                        b-=1;
                        a-=5;
                    }
                    else
                    {
                        a-=9;
                    }
                }
            }
        }
        if(b>0)
        {
            xx+=b/9;
            b=b%9;
            if(b>0)
            {
                xx++;
                a-=36-b*4;
            }
        }
        if(a>0)
        {
            xx+=a/36;
            a=a%36;
            if(a>0)
            {
                xx++;
            }
        }
        printf("%d\n",xx);
    }
    return 0;
}