#include <stdio.h>

int main()
{
    int a,b,c,d,e,f,xx=0;//xx表示需要的6*6的包装数
    while(scanf("%d%d%d%d%d%d",&a,&b,&c,&d,&e,&f)&&a+b+c+d+e+f!=0)//a,b,c,d,e,f分别表示1*1,2*2,3*3,4*4,5*5,6*6的货物数
    {
        xx=f;
        if(e){
            xx+=e;
            if(a){
                a-=11*e;
                if(a<0){
                    a=0;
                }
            }
        }
        if(d){
            xx+=d;
            if(b){
                b-=5*d;
                if(b<0){
                    a+=b*4;
                    b=0;
                }
            }
        }
        if(c){
            xx+=c/8;
            c%=8;
            if(c){
                xx++;
                if(c==1||c==2||c==3){
                    b-=19-4*--c;
                    if(b<0){
                        a+=b*8;
                        b=0;
                    }
                }
                if(c==4){
                    b-=9;
                    if(b<0){
                        a+=b*8;
                        b=0;
                    }
                }
                if(c==5){
                    b-=5;
                    if(b<0){
                        a+=b*8;
                        b=0;
                    }
                }
                if(c==6){
                    b-=3;
                    if(b<0){
                        a+=b*8;
                        b=0;
                    }
                }
                if(c==7){
                    b-=1;
                    if(b<0){
                        a+=b*8;
                        b=0;
                    }
                }
            }
        }
        printf("%d\n",xx);
    }
    return 0;
}